apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: classy-ub-01a
  namespace: cormac-ns
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.19.0.0/12"]
    pods:
      cidrBlocks: ["192.12.0.0/16"]
  topology:
    class: tanzukubernetescluster
    version: v1.23.8---vmware.2-tkg.2-zshippable
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
          name: node-pool-1
          replicas: 2
    variables:
      - name: vmClass
        value: guaranteed-small
      - name: storageClass
        value: vsan-default-storage-policy
